server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/jinhyeon/IdeaProjects/git-local-repo
#          default-label: main