server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/native
        git:
#          uri: file:///Users/jinhyeon/IdeaProjects/git-local-repo
          uri: https://github.com/qwe5507/spring-cloud-config.git
#          username: [your username]
#          password: [your password]
#          default-label: main

management:
  endpoints:
    web:
      exposure:
        exclude: health, busrefresh

encrypt:
  key: abcdefghijklmnopqrstuvwsyz0123456789